dist: xenial
language: python
python:
  - '3.7'

install:
  - pip install pipenv
  - pipenv install

script:
    - pipenv run travis-sphinx build --source docs

after_success:
    - pipenv run travis-sphinx deploy
